# --- étape de build ---
FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY cmd ./cmd
COPY internal ./internal
RUN CGO_ENABLED=0 go build -o /out/gateway ./cmd/gateway

# --- image finale (minimale) ---
FROM alpine:3.20
RUN adduser -D -H sentinel
COPY --from=build /out/gateway /usr/local/bin/gateway
COPY configs /app/configs
WORKDIR /app
USER sentinel
EXPOSE 8080
ENTRYPOINT ["gateway", "-config", "/app/configs/config.json"]
